[package]
name = "nest-repository"
version = "0.1.0"
authors = ["Benjamin Grange <benjamin.grange@epitech.eu>"]

[dependencies]
rocket = "0.3"
rocket_codegen = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
lazy_static = "1.0"
regex = "0.2"

[dependencies.rocket_contrib]
version = "0.3"
default-features = false
features = ["json", "handlebars_templates"]
